name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore 2022 Packages
      run: nuget restore src.2022\NordTheme.sln

    - name: Fixing Missing DLL
      run: |
        echo %userprofile%
        xcopy src.2022\Libraries\Microsoft.VisualStudio.Pkgdef.dll %userprofile%\.nuget\packages\microsoft.visualstudio.vsixcolorcompiler\17.0.31410.258\ /y
      shell: cmd

    - name: Build 2022 Extension
      run: msbuild src.2022\NordTheme.sln /p:Configuration=Release /t:Rebuild
      env: 
        DeployExtension: False

    - name: Restore 2019 Packages
      run: nuget restore src.2019\NordTheme.sln

    - name: Build 2019 Extension
      run: msbuild src.2019\NordTheme.sln /p:Configuration=Release /t:Rebuild
      env: 
        DeployExtension: False

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./package.json

    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Copy VSIX to Releases
      uses: softprops/action-gh-release@v1
      id: create_release
      if: steps.create_tag.outputs.successful
      with:
        draft: false
        prerelease: false
        tag_name: ${{ steps.create_tag.outputs.version }}
        files: |
          src.2022\NordTheme\bin\Release\NordTheme.vsix
          src.2019\NordTheme\bin\Release\NordTheme.2019.vsix
        body: |
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
